## PANDAS

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=['row1','row2','row3','row4','row5'], columns=['col1','col2','col3','col4'])

In [5]:
df.head()

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

## Indexing

In [6]:
# makeCSV
# df.to_csv('temp.csv')

In [24]:
df.iloc[0,:2]

col1    0
col2    1
Name: row1, dtype: int32

In [26]:
df.iloc[:3].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
df['col1']

row1     0
row2     4
row3     8
row4    12
row5    16
Name: col1, dtype: int32

In [32]:
df[['col1', 'col2']]

      col1  col2
row1     0     1
row2     4     5
row3     8     9
row4    12    13
row5    16    17

## In-built Functions

In [28]:
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [29]:
df.col1.value_counts()

12    1
4     1
16    1
8     1
0     1
Name: col1, dtype: int64

In [30]:
df.col2.unique()

array([ 1,  5,  9, 13, 17], dtype=int64)

In [42]:
df.dtypes

## read from CSV

In [35]:
df = pd.read_csv('mercedesbenz.csv')
# df = pd.read_csv('mercedesbenz.csv', usecols=[column names which needs to include ])
# df = pd.read_csv('mercedesbenz.csv', dtypes=['col1':int, 'col2':float, 'col3':'int64'])
# df = pd.read_csv('mercedesbenz.csv', index_col=0) #SPECIFY COLUMN AS INDEX
# df = pd.read_csv('mercedesbenz.csv', index_col=False) #take csv as it is

In [36]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [38]:
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [39]:
df.corr()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
ID,1.000000,-0.055108,0.001602,NaN,0.058988,-0.031917,-0.025438,0.002237,-0.036480,-0.038171,...,0.045229,-0.080259,-0.022965,0.030371,0.023382,-0.013577,-0.038171,-0.009332,-0.015355,0.029059
y,-0.055108,1.000000,-0.026985,NaN,0.089792,0.048276,0.193643,0.023116,0.048946,-0.159815,...,0.029100,0.114005,0.061403,-0.258679,0.067919,0.040932,-0.159815,0.040291,-0.004591,-0.022280
X10,0.001602,-0.026985,1.000000,NaN,-0.033084,-0.028806,-0.100474,-0.002532,-0.005944,-0.010164,...,0.165277,-0.028618,-0.074244,-0.016870,-0.011374,-0.010479,-0.010164,-0.004740,-0.002532,-0.004387
X11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
X12,0.058988,0.089792,-0.033084,NaN,1.000000,0.214825,-0.246513,-0.006212,-0.014584,-0.024937,...,-0.107864,-0.070214,0.030134,-0.016043,-0.027907,-0.005566,-0.024937,-0.011628,-0.006212,-0.010765
X13,-0.031917,0.048276,-0.028806,NaN,0.214825,1.000000,-0.083141,-0.005409,-0.012698,-0.021713,...,-0.169721,-0.061136,0.357229,-0.036040,-0.024299,0.023045,-0.021713,-0.010125,0.041242,-0.009373
X14,-0.025438,0.193643,-0.100474,NaN,-0.246513,-0.083141,1.000000,-0.018865,-0.044291,0.012713,...,0.118950,0.026496,-0.097464,-0.037958,0.103309,0.007743,0.012713,0.023604,0.025199,0.043667
X15,0.002237,0.023116,-0.002532,NaN,-0.006212,-0.005409,-0.018865,1.000000,-0.001116,-0.001908,...,-0.014917,-0.005373,0.032168,-0.003168,-0.002136,-0.001968,-0.001908,-0.000890,-0.000475,-0.000824
X16,-0.036480,0.048946,-0.005944,NaN,-0.014584,-0.012698,-0.044291,-0.001116,1.000000,-0.004480,...,-0.025036,-0.012615,0.045461,-0.007437,-0.005014,-0.004619,-0.004480,-0.002089,-0.001116,-0.001934
X17,-0.038171,-0.159815,-0.010164,NaN,-0.024937,-0.021713,0.012713,-0.001908,-0.004480,1.000000,...,-0.059883,-0.021571,-0.059327,-0.012716,-0.008573,-0.007899,1.000000,-0.003572,-0.001908,-0.003307
X18,-0.027063,-0.001789,-0.010323,NaN,-0.025327,-0.010525,-0.076916,-0.001938,-0.004550,0.085256,...,0.037446,-0.021908,-0.013853,0.043885,-0.008707,-0.008022,0.085256,0.062481,-0.001938,-0.003359
X19,-0.012762,-0.168895,-0.038610,NaN,-0.094730,-0.082482,-0.287691,-0.007250,-0.017020,-0.029102,...,0.118184,-0.081943,0.051426,-0.048305,-0.032569,-0.021140,-0.029102,-0.013571,-0.007250,-0.012563
X20,0.063216,-0.095148,-0.047393,NaN,-0.116280,-0.043126,-0.353137,-0.008899,-0.020892,-0.027905,...,-0.025680,-0.080123,-0.010522,-0.059294,-0.025979,-0.006485,-0.027905,0.000008,-0.008899,-0.015421
X21,-0.029946,0.031111,-0.005944,NaN,-0.014584,0.007215,-0.044291,-0.001116,-0.002620,-0.004480,...,0.064834,-0.012615,-0.024677,-0.007437,-0.005014,-0.004619,-0.004480,-0.002089,-0.001116,-0.001934
X22,-0.096610,-0.094320,-0.035836,NaN,-0.087924,0.226530,-0.267021,-0.006729,-0.015797,-0.017304,...,-0.084487,-0.076055,0.320950,-0.044834,-0.030229,-0.027849,-0.017304,-0.012596,-0.006729,-0.011660
X23,-0.010612,-0.078676,-0.016870,NaN,-0.041391,-0.036040,-0.125703,-0.003168,-0.007437,-0.012716,...,0.011684,-0.035804,-0.040945,-0.009369,-0.014230,-0.013110,-0.012716,-0.005930,-0.003168,-0.005489
X24,-0.008972,-0.003526,-0.005067,NaN,-0.012433,-0.010825,-0.004686,-0.000951,-0.002234,-0.003820,...,-0.029856,-0.010755,-0.029579,-0.006340,-0.004274,-0.003938,-0.003820,0.132088,-0.000951,-0.001649
X26,-0.048634,-0.021173,-0.008223,NaN,-0.020175,-0.017566,-0.061270,-0.001544,-0.003625,0.226724,...,-0.026740,-0.017451,0.039127,-0.010288,-0.006936,-0.006390,0.226724,-0.002890,-0.001544,-0.002675
X27,0.004214,-0.053483,0.070276,NaN,0.184599,0.110191,0.126863,-0.031974,-0.075065,0.059687,...,0.139066,-0.042846,0.043493,0.099070,0.051013,-0.035398,0.059687,0.002780,-0.031974,0.025765
X28,0.030967,-0.250288,-0.021300,NaN,-0.052259,-0.039773,-0.158707,-0.003999,-0.009389,0.045600,...,-0.096764,-0.045204,-0.083969,0.434454,-0.017967,-0.016553,0.045600,-0.007486,-0.003999,-0.006930
X29,0.004175,-0.379629,-0.024615,NaN,-0.042617,-0.052586,-0.076904,-0.004622,-0.010851,0.412903,...,-0.145030,-0.052242,-0.143683,0.685348,-0.020764,-0.019130,0.412903,-0.008652,-0.004622,-0.008009
X30,0.015264,-0.043247,-0.007820,NaN,-0.019185,-0.016705,-0.058265,-0.001468,-0.003447,-0.005894,...,-0.030861,-0.016596,-0.045644,-0.009783,-0.006596,-0.006077,-0.005894,-0.002748,-0.001468,-0.002544
X31,-0.040157,-0.086976,-0.044248,NaN,-0.126861,-0.095558,-0.313459,-0.011996,-0.028163,0.068420,...,0.029181,-0.087163,0.012263,0.133582,0.085267,0.032050,0.068420,0.005156,-0.011996,-0.020787
X32,0.013217,0.001750,-0.012340,NaN,-0.030276,-0.026362,-0.091947,-0.002317,-0.005440,-0.009301,...,0.014625,0.256028,-0.072029,-0.015438,-0.010409,-0.009590,-0.009301,-0.004337,-0.002317,-0.004015
X33,0.015306,-0.014664,-0.001790,NaN,-0.004392,-0.003824,0.017817,-0.000336,-0.000789,-0.001349,...,0.022532,-0.003799,-0.010449,-0.002240,-0.001510,-0.001391,-0.001349,-0.000629,-0.000336,-0.000582
X34,-0.008026,0.061151,-0.008608,NaN,-0.021119,-0.018388,-0.064136,-0.001616,-0.003794,-0.006488,...,-0.016136,-0.018268,0.046906,-0.010769,-0.007261,-0.006689,-0.006488,-0.003025,-0.001616,-0.002801
X35,-0.040157,-0.086976,-0.044248,NaN,-0.126861,-0.095558,-0.313459,-0.011996,-0.028163,0.068420,...,0.029181,-0.087163,0.012263,0.133582,0.085267,0.032050,0.068420,0.005156,-0.011996,-0.020787
X36,0.011691,-0.016999,-0.007820,NaN,-0.019185,-0.016705,-0.058265,-0.001468,-0.003447,-0.005894,...,-0.030861,-0.016596,0.007774,-0.009783,-0.006596,-0.006077,-0.005894,-0.002748,-0.001468,-0.002544
X37,-0.040157,-0.086976,-0.044248,NaN,-0.126861,-0.095558,-0.313459,-0.011996,-0.028163,0.068420,...,0.029181,-0.087163,0.012263,0.133582,0.085267,0.032050,0.068420,0.005156,-0.011996,-0.020787
X38,0.256003,0.012614,-0.021539,NaN,0.017543,-0.029005,0.061752,-0.004044,-0.009495,-0.016235,...,-0.010342,0.045529,-0.034439,-0.026948,-0.018169,0.012864,-0.016235,-0.007571,-0.004044,-0.007008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
X355,0.041805,0.124188,0.139665,NaN,-0.037512,-0.192270,0.056933,0.027828,-0.040107,-0.000969,...,-0.058244,0.110225,0.122234,-0.086310,-0.016217,0.055039,-0.000969,0.052093,0.005373,-0.029603
X356,-0.038715,-0.019163,-0.048979,NaN,-0.046559,-0.116168,-0.208902,0.018175,0.048728,-0.040988,...,-0.320387,-0.043518,0.618954,-0.068033,-0.045870,0.102867,-0.040988,0.071977,-0.010210,-0.017693
X357,-0.021326,-0.016526,-0.004005,NaN,-0.009826,-0.008555,0.039858,-0.000752,-0.001765,-0.003019,...,-0.023595,-0.008499,-0.023376,-0.005010,-0.003378,-0.003112,-0.003019,-0.001408,-0.000752,-0.001303
X358,-0.016827,-0.020961,-0.100230,NaN,0.085827,0.283290,0.161773,-0.018820,0.002857,0.046107,...,0.026843,-0.165170,-0.134136,0.131178,-0.064744,-0.018867,0.046107,0.011922,0.003220,0.043773
X359,-0.033066,-0.014465,-0.021057,NaN,-0.051664,0.007134,0.168556,-0.003954,-0.009282,0.155503,...,0.026934,-0.033041,-0.061724,-0.026345,0.010134,-0.016364,0.155503,-0.007401,-0.003954,-0.006851
X360,0.040947,0.129839,-0.033422,NaN,0.236848,0.341697,0.005676,-0.006276,0.002774,-0.025192,...,0.015984,-0.044002,0.076279,-0.041814,-0.009767,-0.006002,-0.025192,-0.011747,-0.006276,-0.010875
X361,-0.028955,0.022974,0.021777,NaN,-0.210335,0.046522,0.085403,0.004089,0.009600,0.016414,...,0.108607,0.046218,0.127114,0.027245,0.018370,0.016924,0.016414,0.007654,0.004089,0.007086
X362,0.032658,-0.039556,0.111496,NaN,-0.083772,-0.258361,-0.108226,-0.000887,0.002576,-0.091158,...,0.033409,0.019659,0.216654,-0.151307,0.074444,-0.014295,-0.091158,0.027518,-0.000887,-0.039350
X363,0.039679,0.108564,0.056725,NaN,0.093726,0.056781,0.227999,0.012459,-0.078781,0.024615,...,-0.022109,0.000759,-0.035467,0.059754,-0.080466,0.039242,0.024615,0.023322,0.012459,0.021589
X364,-0.063217,0.001008,-0.006209,NaN,-0.015234,0.005803,0.061799,-0.001166,-0.002737,-0.004680,...,-0.017460,-0.013178,-0.026649,-0.007768,-0.005238,-0.004825,-0.004680,-0.002182,0.407763,-0.002020
X365,-0.063217,0.001008,-0.006209,NaN,-0.015234,0.005803,0.061799,-0.001166,-0.002737,-0.004680,...,-0.017460,-0.013178,-0.026649,-0.007768,-0.005238,-0.004825,-0.004680,-0.002182,0.407763,-0.002020
X366,-0.016526,-0.001777,-0.004005,NaN,-0.009826,0.020960,0.039858,-0.000752,-0.001765,-0.003019,...,0.006006,-0.008499,-0.008525,-0.005010,-0.003378,-0.003112,-0.003019,-0.001408,0.632230,-0.001303
X367,0.037122,0.100708,-0.027139,NaN,-0.066587,-0.057978,0.226781,-0.005096,0.030034,-0.020456,...,-0.159900,-0.057598,0.340191,-0.033954,-0.022893,-0.009114,-0.020456,-0.009539,-0.005096,-0.008830
X368,0.006228,0.101059,-0.030039,NaN,-0.062547,-0.047400,-0.087187,-0.005640,-0.013242,0.022482,...,-0.107600,-0.059536,0.098935,-0.010034,-0.025339,0.009496,0.022482,0.013489,-0.005640,-0.009774
X369,-0.007621,0.015230,-0.002532,NaN,-0.006212,-0.005409,-0.018865,-0.000475,-0.001116,-0.001908,...,-0.014917,-0.005373,-0.014779,-0.003168,-0.002136,0.241611,-0.001908,-0.000890,-0.000475,-0.000824
X370,0.087520,0.056700,-0.009503,NaN,-0.023315,-0.020301,-0.070807,-0.001784,-0.004189,-0.007163,...,-0.055989,0.332060,-0.055469,-0.011889,-0.008016,-0.007385,-0.007163,-0.003340,-0.001784,-0.003092
X371,0.002822,-0.215375,-0.013964,NaN,-0.034261,-0.029832,-0.091899,-0.002622,-0.006156,-0.010526,...,-0.082275,-0.029636,-0.081511,-0.017471,-0.011779,-0.010852,-0.010526,-0.004908,-0.002622,-0.004544
X372,-0.022628,-0.036545,-0.002532,NaN,-0.006212,-0.005409,-0.018865,-0.000475,-0.001116,-0.001908,...,-0.014917,-0.005373,-0.014779,-0.003168,-0.002136,-0.001968,-0.001908,-0.000890,-0.000475,-0.000824
X373,0.005930,-0.058952,-0.016266,NaN,0.176659,-0.034749,-0.054797,-0.003054,-0.007170,-0.012261,...,-0.095837,-0.034522,-0.094947,-0.020351,-0.013721,-0.012641,-0.012261,-0.005717,-0.003054,-0.005293
X374,0.014103,0.015378,-0.062993,NaN,0.097125,-0.134572,-0.008845,-0.011828,-0.005563,-0.047481,...,-0.371145,-0.133691,-0.367698,-0.078811,-0.053137,-0.048954,-0.047481,-0.022141,0.014182,-0.020496
X375,0.045229,0.029100,0.165277,NaN,-0.107864,-0.169721,0.118950,-0.014917,-0.025036,-0.059883,...,1.000000,-0.168611,-0.463738,-0.099396,-0.067016,-0.061741,-0.059883,-0.015413,-0.014917,0.055225
X376,-0.080259,0.114005,-0.028618,NaN,-0.070214,-0.061136,0.026496,-0.005373,-0.012615,-0.021571,...,-0.168611,1.000000,-0.167045,-0.035804,-0.024140,-0.022240,-0.021571,-0.010059,-0.005373,-0.009311
X377,-0.022965,0.061403,-0.074244,NaN,0.030134,0.357229,-0.097464,0.032168,0.045461,-0.059327,...,-0.463738,-0.167045,1.000000,-0.098473,-0.066393,-0.061168,-0.059327,0.035107,0.008694,-0.025610
X378,0.030371,-0.258679,-0.016870,NaN,-0.016043,-0.036040,-0.037958,-0.003168,-0.007437,-0.012716,...,-0.099396,-0.035804,-0.098473,1.000000,-0.014230,-0.013110,-0.012716,-0.005930,-0.003168,-0.005489
X379,0.023382,0.067919,-0.011374,NaN,-0.027907,-0.024299,0.103309,-0.002136,-0.005014,-0.008573,...,-0.067016,-0.024140,-0.066393,-0.014230,1.000000,-0.008839,-0.008573,-0.003998,-0.002136,-0.003701
X380,-0.013577,0.040932,-0.010479,NaN,-0.005566,0.023045,0.007743,-0.001968,-0.004619,-0.007899,...,-0.061741,-0.022240,-0.061168,-0.013110,-0.008839,1.000000,-0.007899,-0.003683,-0.001968,-0.003410
X382,-0.038171,-0.159815,-0.010164,NaN,-0.024937,-0.021713,0.012713,-0.001908,-0.004480,1.000000,...,-0.059883,-0.021571,-0.059327,-0.012716,-0.008573,-0.007899,1.000000,-0.003572,-0.001908,-0.003307
X383,-0.009332,0.040291,-0.004740,NaN,-0.011628,-0.010125,0.023604,-0.000890,-0.002089,-0.003572,...,-0.015413,-0.010059,0.035107,-0.005930,-0.003998,-0.003683,-0.003572,1.000000,-0.000890,-0.001542
X384,-0.015355,-0.004591,-0.002532,NaN,-0.006212,0.041242,0.025199,-0.000475,-0.001116,-0.001908,...,-0.014917,-0.005373,0.008694,-0.003168,-0.002136,-0.001968,-0.001908,-0.000890,1.000000,-0.000824
X385,0.029059,-0.022280,-0.004387,NaN,-0.010765,-0.009373,0.043667,-0.000824,-0.001934,-0.003307,...,0.055225,-0.009311,-0.025610,-0.005489,-0.003701,-0.003410,-0.003307,-0.001542,-0.000824,1.000000

## useful for NLP

In [43]:
data = 'a,b\n"hello, \\"Bob\\", nice to see you", 5'

In [44]:
data

'a,b\n"hello, \\"Bob\\", nice to see you", 5'

In [45]:
from io import StringIO, BytesIO

In [46]:
pd.read_csv(StringIO(data), escapechar='\\')

                               a  b
0  hello, "Bob", nice to see you  5

## jSON

In [47]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
pd.read_json(Data)

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."